# Generated by Django 3.0.6 on 2020-05-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20200518_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
