# Generated by Django 3.0.6 on 2020-05-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20200518_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
